{
    'name': 'Ram CRM',
    'author': "Surge Technologies",
    'license': 'Other proprietary',
    'summary': 'Ram Clinics CRM',
    'version': '0.2',
    'description': """ Ram Clinics CRM """,
    'depends': ['web', 'mail', 'crm', 'helpdesk', 'sms'],
    'data': [
        'data/res.company.xml',
        'data/crm.lost.reason.csv',
        'data/groups.xml',
        'data/cz.lead.stage4.csv',
        'data/cz.lead.status.csv',
        'security/ir.model.access.csv',
        'security/lead_rule.xml',
        'security/crm_activity.xml',
        'security/lead_4_ram_stats_rule.xml',
        'security/helpdesk_ticket.xml',
        'security/helpdesk_team.xml',
        'data/general.xml',
        'data/crm.stage.csv',
        'data/clinizone.business_category.csv',
        'data/utm.source.csv',
        'views/ramcrm.xml',
        'wizard/blacklisted_phone_wizard.xml',
        'wizard/assign_agent_wizard.xml',
        'reports/stats/stats_report_template.xml',
        'reports/stats/stats_report_wizard.xml',
        'reports/stats2/stats2_template.xml',
        'reports/stats2/stats2_wizard.xml',
        'views/activity_report_view.xml',
        'views/crm_stage_form.xml',
        'views/lead_search.xml',
        'views/lead_stats.xml',
        'views/lead_form.xml',
        'views/lead_tree.xml',
        'views/lead_kanban.xml',
        'views/department/department_tree.xml',
        'views/department/department_form.xml',
        'views/department/department_action.xml',
        'views/department/department_menu.xml',
        'views/service/service_tree.xml',
        'views/service/service_form.xml',
        'views/service/service_action.xml',
        'views/service/service_menu.xml',
        'views/city/city_tree.xml',
        'views/city/city_form.xml',
        'views/city/city_action.xml',
        'views/city/city_menu.xml',
        'views/branch/branch_tree.xml',
        'views/branch/branch_action.xml',
        'views/branch/branch_menu.xml',
        'views/blacklist/blacklist_tree.xml',
        'views/blacklist/blacklist_action.xml',
        'views/blacklist/blacklist_menu.xml',
        'views/ram_case/ram_case_source_tree.xml',
        'views/ram_case/ram_case_form.xml',
        'views/ram_case/ram_case_tree.xml',
        'views/helpdesk/stage_form.xml',
        'views/helpdesk/team_tree.xml',
        'views/helpdesk/team_form.xml',
        'templates/portal_user_home.xml',
        'data/mail.activity.type.csv',
        'views/activity_pivot_view.xml',
        'views/activity_action.xml',
        'views/activity_menu.xml',
        'views/lead_4_ram_stats/tree.xml',
        'views/lead_4_ram_stats/graph.xml',
        'views/lead_4_ram_stats/action.xml',
        'views/lead_4_ram_stats/menu.xml',
        'views/lead_4_ram_stats/search.xml',
        'views/lead_source/lead_source_tree.xml',
        'views/lead_source/lead_source_form.xml',
        'views/lead_source/lead_source_action.xml',
        'views/lead_source/lead_source_menu.xml',
        'data/helpdesk.ticket.type.csv',
        'data/clinizone.lead_source.csv',
        'data/helpdesk_menu.xml',
        'data/cron.xml',
        'data/sms.template.xml',
        'data/helpdesk.team.csv',
        'views/company/form.xml',
        'views/ticket_team_assignment_rule/tree.xml',
        'views/ticket_team_assignment_rule/action.xml',
        'views/ticket_team_assignment_rule/menu.xml',
        'security/ticket_team_assignment_rule.xml',
        'views/helpdesk/ticket_type/list.xml',
        'views/helpdesk/ticket_type/action.xml',
        'views/helpdesk/ticket_type/menu.xml',
    ],
    'demo': [
        'demo/city.xml',
        'demo/branch.xml',
        'demo/department.xml',
        'demo/service.xml',
        'demo/crm.lead.csv',
    ],
    'installable': True,
    'application': True,
}
