{
    'name': 'Medical Audit',
    'license': 'Other proprietary',
    'summary': 'Medical Audit',
    'version': '0.1',
    'description': """ CliniZone Medical Audit """,
    'depends': ['web', 'mail', 'crm', 'helpdesk', 'ramcrm'],
    'data': [
        'data/groups.xml',
        'data/clinizone.team.csv',
        'data/cron.xml',
        'security/ir.model.access.csv',
        'views/medical_audit_tree.xml',
        'views/audit_teams_tree.xml',
        'views/medical_audit_form.xml',
        'views/medical_audit_action.xml',
        'views/dental/dental_audit_tree.xml',
        'views/dental/dental_audit_form.xml',
        'views/dental/dental_audit_action.xml',
        'views/audit_teams_action.xml',
        'views/medical_audit_menu.xml',
        'views/dental/dental_audit_menu.xml',
        'views/prime_care_branch/prime_care_branch_tree.xml',
        'views/prime_care_branch/prime_care_branch_action.xml',
        'views/prime_care_branch/prime_care_branch_menu.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'application': True,
}
