{
    'name': "Missed Invoices",
    'summary': "Access Prime Care to get pending invoice and create leads",
    'description': """
A module to access Prime Care to get pending invoice and create leads.
    """,
    'author': "Topbusiness",
    'website': "https://topbusiness.io",
    'category': 'API Integration',
    'version': '0.3',
    'sequence': 1,
    'license': 'Other proprietary',

    'depends': ['base', 'ramcrm', 'cz_prime_care'],

    'data': [
        'security/ir.model.access.csv',
        'data/ir.config_parameter.xml',
        'data/clinizone.lead_source.csv',
        'data/utm.source.csv',
        'views/pending_invoice/list.xml',
        'views/pending_invoice/action.xml',
        'views/pending_invoice/menu.xml',
        'views/above_amount_invoice/list.xml',
        'views/above_amount_invoice/action.xml',
        'views/above_amount_invoice/menu.xml',
        'views/pending_referral/list.xml',
        'views/pending_referral/action.xml',
        'views/pending_referral/menu.xml',
        'views/dna_appointment/list.xml',
        'views/dna_appointment/action.xml',
        'views/dna_appointment/menu.xml',
        'views/booked_appointment/list.xml',
        'views/booked_appointment/action.xml',
        'views/booked_appointment/menu.xml',
        'views/company.xml',
        'views/above_amount_company.xml',
        'views/pending_referral_company.xml',
        'views/dna_appointment_company.xml',
        'views/booked_appointment_company.xml',
        'demo/ir.cron.xml',
        'demo/above_amount_ir.cron.xml',
        'demo/pending_referral_ir.cron.xml',
        'demo/dna_appointment_ir.cron.xml',
        'demo/booked_appointment_ir.cron.xml',
        'demo/pending_invoice_opportunity_cron.xml',
    ],
    'demo': [
        'demo/res.company.xml',
        'demo/clinizone.branch.csv',
        'demo/clinizone.department.csv',
    ],
}

